AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  URI:
    Type: String
    Description: The URI used to name resources [projectName-env-gitUsername]
  Env:
    Type: String
    Default: dev
    Description: The environment variables for Lambda
    AllowedValues:
      - dev
      - production
      - staging

Resources:
  Lambda:
    Type: 'AWS::Serverless::Function'
    DependsOn: LamdaLogGroup
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: '../'
      DockerTag: nodejs14.x-v1
    Properties:
      FunctionName: !Sub '${URI}-lambda'
      PackageType: Image
      Timeout: 20
      MemorySize: 1024
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:BatchGet*
                - dynamodb:DescribeStream
                - dynamodb:DescribeTable
                - dynamodb:Get*
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchWrite*
                - dynamodb:CreateTable
                - dynamodb:Delete*
                - dynamodb:Update*
                - dynamodb:PutItem
              Resource: '*'
      Environment:
        Variables:
          Env: !Ref Env

  LamdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub '/aws/lambda/${URI}-lambda'
      RetentionInDays: 14
